gdb-multiarch kernel/kernel \
  -ex "set architecture riscv:rv64" \
  -ex "target remote localhost:26000" \
  -ex "break print_loop" \
  -ex "layout split" \
  -ex "continue" \
  -ex "continue" \
  -ex "continue" \
  -ex "continue" \
  -ex "continue" \
  -ex "continue" \
  -ex "continue" \
  -ex "continue" \
  -ex "continue" \
  -ex "continue" \
  -ex "continue" \
  -ex "continue" \
  -ex "continue" \
  -ex "continue" \
  -ex "continue" \
  -ex "continue" \
  -ex "continue" \
  -ex "continue" \
  -ex "continue" \
  -ex "continue" \
  -ex "continue" \
  -ex "continue" \
  -ex "continue" \
  -ex "continue" \
  -ex "continue" \
  -ex "continue" \
  -ex "continue" \
  -ex "continue" \
  -ex "continue" \
  -ex "continue" 
