print "# generated by usys.pl - do not edit\n";

my %syscalls = (
    'myHelloWorld' => 1,
);

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "$name:\n";
    print " li a7, $syscalls{$name}\n";
    print " j uservec\n\n";
    print " ret\n";
}

entry("myHelloWorld");